### ISSUE TITLE
QUESTION should the permission provider use separate permissions for create/edit/delete?

### ISSUE THREAD

**Issue by muskie9** [dynamic/SilverStripe-Locator-Module#46]
In FoxyStripe we're using an all encompassing canCRUD. I'm wondering if there would be instances where someone would have create OR edit access but not the other. I could see delete being broken out, but create/edit seems almost one in the same in most cases.

**Comment by muskie9** [comment]
This could also cause a breakage in certain installations that have existing permissions set. We'll want to tag a release if this is worked into an update and have a note regarding upgrading to the tagged release.

**Comment by jirish** [comment]
I think it would be smart to breakup Create, Read, Update and Delete, like we did for Locator. It’s a couple extra clicks, but a lot more flexible for huge stores with multiple people working in them.


Jason Irish

CTO




Dynamic

Digital(+) Agency

1526 S. 12th St

Sheboygan, WI 53081




JIrish@DynamicDoes.com

http://DynamicDoes.com

P: (920) 459-8889





A member of Worldwide Partners Inc. The world's largest owner-operated agency network.
